/**
 * UK NHS trusts, integrated care boards, and devolved-nation health organisations for logbook autocomplete.
 * Only names from this list are accepted (no free text sites).
 */
export const UK_NHS_TRUSTS: readonly string[] = [
  'Aneurin Bevan University Health Board',
  'Barking, Havering and Redbridge University Hospitals NHS Trust',
  'Barnsley Hospital NHS Foundation Trust',
  'Bedford Hospital NHS Trust',
  'Bedfordshire Hospitals NHS Foundation Trust',
  'Belfast Health and Social Care Trust',
  'Betsi Cadwaladr University Health Board',
  'Birmingham Women\'s and Children\'s NHS Foundation Trust',
  'Blackpool Teaching Hospitals NHS Foundation Trust',
  'Bolton NHS Foundation Trust',
  'Bradford Teaching Hospitals NHS Foundation Trust',
  'Buckinghamshire Healthcare NHS Trust',
  'Calderdale and Huddersfield NHS Foundation Trust',
  'Cambridge University Hospitals NHS Foundation Trust',
  'Cardiff and Vale University Health Board',
  'Chesterfield Royal Hospital NHS Foundation Trust',
  'County Durham and Darlington NHS Foundation Trust',
  'Croydon Health Services NHS Trust',
  'Cwm Taf Morgannwg University Health Board',
  'Dartford and Gravesham NHS Trust',
  'Derbyshire Community Health Services NHS Foundation Trust',
  'Derbyshire Healthcare NHS Foundation Trust',
  'Doncaster and Bassetlaw Teaching Hospitals NHS Foundation Trust',
  'Dorset County Hospital NHS Foundation Trust',
  'East Cheshire NHS Trust',
  'East Kent Hospitals University NHS Foundation Trust',
  'East Lancashire Hospitals NHS Trust',
  'East Suffolk and North Essex NHS Foundation Trust',
  'East Sussex Healthcare NHS Trust',
  'Epsom and St Helier University Hospitals NHS Trust',
  'Frimley Health NHS Foundation Trust',
  'Gateshead Health NHS Foundation Trust',
  'George Eliot Hospital NHS Trust',
  'Gloucestershire Hospitals NHS Foundation Trust',
  'Great Ormond Street Hospital for Children NHS Foundation Trust',
  'Great Western Hospitals NHS Foundation Trust',
  'Guy\'s and St Thomas\' NHS Foundation Trust',
  'Hampshire Hospitals NHS Foundation Trust',
  'Harrogate and District NHS Foundation Trust',
  'Hull University Teaching Hospitals NHS Trust',
  'Hywel Dda University Health Board',
  'Imperial College Healthcare NHS Trust',
  'Isle of Wight NHS Trust',
  'James Paget University Hospitals NHS Foundation Trust',
  'King\'s College Hospital NHS Foundation Trust',
  'Kingston Hospital NHS Foundation Trust',
  'Lancashire Teaching Hospitals NHS Foundation Trust',
  'Leeds Teaching Hospitals NHS Trust',
  'Lewisham and Greenwich NHS Trust',
  'Liverpool University Hospitals NHS Foundation Trust',
  'London North West University Healthcare NHS Trust',
  'Luton and Dunstable University Hospital NHS Foundation Trust',
  'Maidstone and Tunbridge Wells NHS Trust',
  'Manchester University NHS Foundation Trust',
  'Medway NHS Foundation Trust',
  'Mid Cheshire Hospitals NHS Foundation Trust',
  'Mid and South Essex NHS Foundation Trust',
  'Milton Keynes University Hospital NHS Foundation Trust',
  'NHS Ayrshire and Arran',
  'NHS Borders',
  'NHS Dumfries and Galloway',
  'NHS Fife',
  'NHS Forth Valley',
  'NHS Grampian',
  'NHS Greater Glasgow and Clyde',
  'NHS Highland',
  'NHS Lanarkshire',
  'NHS Lothian',
  'NHS Orkney',
  'NHS Shetland',
  'NHS Tayside',
  'NHS Western Isles',
  'Norfolk and Norwich University Hospitals NHS Foundation Trust',
  'North Bristol NHS Trust',
  'North Cumbria Integrated Care NHS Foundation Trust',
  'Northern Care Alliance NHS Foundation Trust',
  'Northern Health and Social Care Trust',
  'Northern Lincolnshire and Goole NHS Foundation Trust',
  'North Middlesex University Hospital NHS Trust',
  'North Tees and Hartlepool NHS Foundation Trust',
  'North West Anglia NHS Foundation Trust',
  'Nottingham University Hospitals NHS Trust',
  'Oxford University Hospitals NHS Foundation Trust',
  'Pennine Acute Hospitals NHS Trust',
  'Peterborough and Stamford Hospitals NHS Foundation Trust',
  'Portsmouth Hospitals University NHS Trust',
  'Powys Teaching Health Board',
  'Princess Alexandra Hospital NHS Trust',
  'Royal Berkshire NHS Foundation Trust',
  'Royal Brompton and Harefield NHS Foundation Trust',
  'Royal Cornwall Hospitals NHS Trust',
  'Royal Devon University Healthcare NHS Foundation Trust',
  'Royal Free London NHS Foundation Trust',
  'Royal National Orthopaedic Hospital NHS Trust',
  'Royal Papworth Hospital NHS Foundation Trust',
  'Royal Surrey NHS Foundation Trust',
  'Royal United Hospitals Bath NHS Foundation Trust',
  'Salisbury NHS Foundation Trust',
  'Sandwell and West Birmingham NHS Trust',
  'Sheffield Children\'s NHS Foundation Trust',
  'Sheffield Teaching Hospitals NHS Foundation Trust',
  'Sherwood Forest Hospitals NHS Foundation Trust',
  'Shrewsbury and Telford Hospital NHS Trust',
  'South Eastern Health and Social Care Trust',
  'Southern Health and Social Care Trust',
  'South Tees Hospitals NHS Foundation Trust',
  'South Warwickshire University NHS Foundation Trust',
  'South West London and St George\'s Mental Health NHS Trust',
  'Southend University Hospital NHS Foundation Trust',
  'St George\'s University Hospitals NHS Foundation Trust',
  'Stockport NHS Foundation Trust',
  'Surrey and Sussex Healthcare NHS Trust',
  'Swansea Bay University Health Board',
  'The Dudley Group NHS Foundation Trust',
  'The Hillingdon Hospitals NHS Foundation Trust',
  'The Rotherham NHS Foundation Trust',
  'The Royal Wolverhampton NHS Trust',
  'The Walton Centre NHS Foundation Trust',
  'The Whittington Hospital NHS Trust',
  'United Lincolnshire Hospitals NHS Trust',
  'University College London Hospitals NHS Foundation Trust',
  'University Hospitals Birmingham NHS Foundation Trust',
  'University Hospitals Bristol and Weston NHS Foundation Trust',
  'University Hospitals Coventry and Warwickshire NHS Trust',
  'University Hospitals Dorset NHS Foundation Trust',
  'University Hospitals of Derby and Burton NHS Foundation Trust',
  'University Hospitals of Leicester NHS Trust',
  'University Hospitals of Morecambe Bay NHS Foundation Trust',
  'University Hospitals of North Midlands NHS Trust',
  'Walsall Healthcare NHS Trust',
  'Warrington and Halton Teaching Hospitals NHS Foundation Trust',
  'Western Health and Social Care Trust',
  'West Hertfordshire Teaching Hospitals NHS Trust',
  'West Suffolk NHS Foundation Trust',
  'Wye Valley NHS Trust',
  'York and Scarborough Teaching Hospitals NHS Foundation Trust',
].sort((a, b) => a.localeCompare(b));

const _set = new Set(UK_NHS_TRUSTS.map((t) => t.toLowerCase()));

export function isOfficialUkNhsTrustName(name: string): boolean {
  return _set.has(name.trim().toLowerCase());
}
